# Generated by Django 4.2.2 on 2023-06-12 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_paragraph_alter_item_image"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Paragraph",
        ),
    ]
