# Generated by Django 4.2.2 on 2023-06-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_delete_paragraph"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="audio",
            field=models.FileField(blank=True, null=True, upload_to="audio"),
        ),
    ]
