# Generated by Django 4.2.2 on 2023-06-13 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_item_audio"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="audio",
        ),
    ]
