# Generated by Django 4.2.2 on 2023-06-14 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_rename_description_item_description1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="audio",
            field=models.FileField(blank=True, null=True, upload_to="audio"),
        ),
    ]
