# Generated by Django 4.2.2 on 2023-06-17 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_item_audio"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="audio",
        ),
        migrations.AddField(
            model_name="item",
            name="description13",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="description14",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="description15",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="description16",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="description17",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="description18",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="description19",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="description20",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="description21",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="description22",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="description23",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="description24",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="description25",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="titlename1",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="titlename10",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="titlename11",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="titlename12",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="titlename13",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="titlename14",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="titlename15",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="titlename16",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="titlename17",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="titlename18",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="titlename19",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="titlename2",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="titlename20",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="titlename21",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="titlename22",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="titlename23",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="titlename24",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="titlename25",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="titlename3",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="titlename4",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="titlename5",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="titlename6",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="titlename7",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="titlename8",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="titlename9",
            field=models.TextField(blank=True, null=True),
        ),
    ]
