# Generated by Django 4.2.2 on 2023-06-17 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_sv"),
    ]

    operations = [
        migrations.AddField(
            model_name="sv",
            name="step10",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sv",
            name="step1",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sv",
            name="step2",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sv",
            name="step3",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sv",
            name="step4",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sv",
            name="step5",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sv",
            name="step6",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sv",
            name="step7",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sv",
            name="step8",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sv",
            name="step9",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sv",
            name="title1",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="sv",
            name="title10",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="sv",
            name="title2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="sv",
            name="title3",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="sv",
            name="title4",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="sv",
            name="title5",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="sv",
            name="title6",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="sv",
            name="title7",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="sv",
            name="title8",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="sv",
            name="title9",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
