# Generated by Django 4.2.2 on 2023-06-26 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_item_description1_remove_item_description10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagesections',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
