# Generated by Django 4.2.2 on 2023-06-26 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_pagesections_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagesections',
            name='name',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
